PrefabFiles = {
    "kisaki",
    "kisaki_items",
    "kisaki_constellation_talismans",
    "kisaki_multivariate_amulet",
    "kisaki_debuffs",
    "kisaki_shadow_protector",
    "kisaki_boxes",
    "kisaki_space_chest",
    "kisaki_yog_key",
    "kisaki_tool",
    "kisaki_projectile",
    "kisaki_complexprojectile",
    "kisaki_packing",
    "kisaki_magic_staff",
}
